### ISSUE TITLE
httpx.ReadTimeout: The read operation timed out

### ISSUE THREAD

**Issue by newjxmaster** [VRSEN/agency-swarm-lab#17]
I get a ReadTimeout how can I increase the 
THREAD:[ PlannerAgent -> Devid ]: URL https://platform.openai.com/playground?assistant=asst_7Fi6GjmuAxHSzxX6Gvv0RM40&mode=assistant&thread=thread_4oI9KfDLCScEtjOU8CuTL656
Exception in thread Thread-7 (get_completion_stream):
Traceback (most recent call last):
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 113, in __iter__
    for part in self._httpcore_stream:
  File "/home/seluser/venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 367, in __iter__
    raise exc from None
  File "/home/seluser/venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 363, in __iter__
    for part in self._stream:
  File "/home/seluser/venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 349, in __iter__
    raise exc
  File "/home/seluser/venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 341, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/seluser/venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 210, in _receive_response_body
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seluser/venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seluser/venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/seluser/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/seluser/venv/lib/python3.11/site-packages/agency_swarm/agency/agency.py", line 147, in get_completion_stream
    next(gen)
  File "/home/seluser/venv/lib/python3.11/site-packages/agency_swarm/threads/thread.py", line 109, in get_completion
    self._submit_tool_outputs(tool_outputs, event_handler)
  File "/home/seluser/venv/lib/python3.11/site-packages/agency_swarm/threads/thread.py", line 227, in _submit_tool_outputs
    stream.until_done()
  File "/home/seluser/venv/lib/python3.11/site-packages/openai/lib/streaming/_assistants.py", line 102, in until_done
    consume_sync_iterator(self)
  File "/home/seluser/venv/lib/python3.11/site-packages/openai/_utils/_streams.py", line 6, in consume_sync_iterator
    for _ in iterator:
  File "/home/seluser/venv/lib/python3.11/site-packages/openai/lib/streaming/_assistants.py", line 69, in __iter__
    for item in self._iterator:
  File "/home/seluser/venv/lib/python3.11/site-packages/openai/lib/streaming/_assistants.py", line 404, in __stream__
    for event in stream:
  File "/home/seluser/venv/lib/python3.11/site-packages/openai/_streaming.py", line 46, in __iter__
    for item in self._iterator:
  File "/home/seluser/venv/lib/python3.11/site-packages/openai/_streaming.py", line 61, in __stream__
    for sse in iterator:
  File "/home/seluser/venv/lib/python3.11/site-packages/openai/_streaming.py", line 53, in _iter_events
    yield from self._decoder.iter(self.response.iter_lines())
  File "/home/seluser/venv/lib/python3.11/site-packages/openai/_streaming.py", line 287, in iter
    for line in iterator:
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_models.py", line 861, in iter_lines
    for text in self.iter_text():
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_models.py", line 848, in iter_text
    for byte_content in self.iter_bytes():
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_models.py", line 883, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_client.py", line 126, in __iter__
    for chunk in self._stream:
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 112, in __iter__
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/seluser/venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

**Comment by berksezer9** [comment]
I have the same issue:

🐧 WebDeveloper 🛠️ Executing Function
Function(arguments='{"command":"build"}', name='RunCommand', output=None)                                                                                                  
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
RunCommand ⚙️ Function Output
Error building the app: b"Failed to compile.\n\n./src/pages/index.tsx:117:9\nType error: Cannot find name 'main'.\n\n\x1b[0m \x1b[90m 115 |\x1b[39m                        
\x1b[33m<\x1b[39m\x1b[33m/\x1b[39m\x1b[33ma\x1b[39m\x1b[33m>\x1b[39m\x1b[0m\n\x1b[0m \x1b[90m 116 |\x1b[39m                                                                
\x1b[33m<\x1b[39m\x1b[33m/\x1b[39m\x1b[33mdiv\x1b[39m\x1b[33m>\x1b[39m\x1b[0m\n\x1b[0m\x1b[31m\x1b[1m>\x1b[22m\x1b[39m\x1b[90m 117 |\x1b[39m                               
\x1b[33m<\x1b[39m\x1b[33m/\x1b[39m\x1b[33mmain\x1b[39m\x1b[33m>\x1b[39m\x1b[0m\n\x1b[0m \x1b[90m     |\x1b[39m         \x1b[31m\x1b[1m^\x1b[22m\x1b[39m\x1b[0m\n\x1b[0m    
\x1b[90m 118 |\x1b[39m     \x1b[33m<\x1b[39m\x1b[33m/\x1b[39m\x1b[33m>\x1b[39m\x1b[0m\n\x1b[0m \x1b[90m 119 |\x1b[39m   )\x1b[33m;\x1b[39m\x1b[0m\n\x1b[0m \x1b[90m 120    
|\x1b[39m }\x1b[0m\n".                                                                                                                                                     

Please make sure to read the problematic file with the FileReader tool and fix the errors. Rewrite the entire file with FileWriter tool if you get stuck.                  
Traceback (most recent call last):
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 113, in __iter__
    for part in self._httpcore_stream:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 367, in __iter__
    raise exc from None
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 363, in __iter__
    for part in self._stream:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 349, in __iter__
    raise exc
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 341, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 210, in _receive_response_body
    event = self._receive_event(timeout=timeout)
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/berks/PycharmProjects/agency-swarm-lab/WebDevCrafters/agency.py", line 27, in <module>
    agency.run_demo()
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/agency_swarm/agency/agency.py", line 565, in run_demo
    self.get_completion_stream(message=text, event_handler=TermEventHandler, recipient_agent=recipient_agent)
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/agency_swarm/agency/agency.py", line 194, in get_completion_stream
    next(res)
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/agency_swarm/threads/thread.py", line 140, in get_completion
    item = next(output)
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/agency_swarm/threads/thread.py", line 167, in get_completion
    self._create_run(recipient_agent, additional_instructions, event_handler, 'required',
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/agency_swarm/threads/thread.py", line 260, in _create_run
    stream.until_done()
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/lib/streaming/_assistants.py", line 102, in until_done
    consume_sync_iterator(self)
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/_utils/_streams.py", line 6, in consume_sync_iterator
    for _ in iterator:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/lib/streaming/_assistants.py", line 69, in __iter__
    for item in self._iterator:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/lib/streaming/_assistants.py", line 404, in __stream__
    for event in stream:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/_streaming.py", line 46, in __iter__
    for item in self._iterator:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/_streaming.py", line 58, in __stream__
    for sse in iterator:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/_streaming.py", line 50, in _iter_events
    yield from self._decoder.iter_bytes(self.response.iter_bytes())
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/_streaming.py", line 280, in iter_bytes
    for chunk in self._iter_chunks(iterator):
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/openai/_streaming.py", line 291, in _iter_chunks
    for chunk in iterator:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpx/_models.py", line 883, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpx/_client.py", line 126, in __iter__
    for chunk in self._stream:
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 114, in __iter__
    yield part
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/berks/PycharmProjects/agency-swarm-lab/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

**Comment by ArtemShatokhin** [comment]
There are multiple reasons why this error can occur. Sometimes it is related to openai itself and completions can fail due to their server issues or in case you hit rate-limit. It could also be caused by connection issues on your own side.
